# Generated by Django 5.2.4 on 2025-07-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Внеочередное новостное событие', max_length=50, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
