# Generated by Django 5.2.4 on 2025-08-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0006_alter_specialist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('therapists', 'Терапевтическая участковая служба'), ('pediatricians', 'Педиатрическая участковая служба'), ('polyclinic', 'Поликлиника'), ('ivenec', 'Ивенецкая горпоселковая больница'), ('rakov', 'Раковская участковая больница')], default='polyclinic', max_length=20, verbose_name='Место приёма')),
                ('monday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Понедельник')),
                ('tuesday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вторник')),
                ('wednesday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Среда')),
                ('thursday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Четверг')),
                ('friday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пятница')),
                ('specialist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='staff.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'График специалиста',
                'verbose_name_plural': 'Графики специалистов',
            },
        ),
    ]
