# Generated by Django 5.2.4 on 2025-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О. сотрудника')),
                ('speciality', models.CharField(max_length=100, verbose_name='Специальность')),
                ('monday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Понедельник')),
                ('tuesday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вторник')),
                ('wednesday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Среда')),
                ('thursday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Четверг')),
                ('friday', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пятница')),
            ],
            options={
                'verbose_name': 'График специалиста',
                'verbose_name_plural': 'Графики специалистов',
            },
        ),
    ]
