# Generated by Django 5.2.4 on 2025-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(choices=[('therapists', 'Терапевтическая участковая служба'), ('pediatricians', 'Педиатрическая участковая служба'), ('polyclinic', 'Поликлиника'), ('ivenec', 'Ивенецкая горпоселковая больница'), ('rakov', 'Раковская участковая больница')], default='polyclinic', max_length=20, verbose_name='Место приёма'),
        ),
    ]
