# Generated by Django 5.2.4 on 2025-08-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_location'),
        ('staff', '0006_alter_specialist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='speciality',
        ),
        migrations.AddField(
            model_name='schedule',
            name='specialist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='staff.specialist', verbose_name='Специалист'),
        ),
    ]
