# Generated by Django 5.2.4 on 2025-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('high_med_education', 'Высшее медицинское образование'), ('secondary_med_education', 'Среднее специальное медицинское образование'), ('high_education', 'Высшее не медицинское образование'), ('secondary_education', 'Среднее не медицинское образование'), ('other', 'Другое')], default='secondary_med_education', max_length=30)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
