# Generated by Django 5.2.4 on 2025-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.CharField(choices=[('admin', 'Администрация'), ('general', 'Общий специалист')], default='general', max_length=20),
        ),
    ]
