# Generated by Django 5.2.4 on 2025-08-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_specialist_bio_specialist_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='specialist',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
