# Generated by Django 5.2.4 on 2025-08-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_specialist_options_specialist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
