# Generated by Django 5.2.4 on 2025-08-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_specialist_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
