# Generated by Django 5.2.4 on 2025-08-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_specialist_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['order'], 'verbose_name': 'Специалиста', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
