# Generated by Django 5.2.4 on 2025-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_specialist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='category',
            field=models.CharField(choices=[('admin', 'Администрация'), ('general', 'Специалисты на странице "Специалисты"'), ('schedule_specialists', 'Специалисты в графике приёма')], default='general', max_length=20),
        ),
    ]
