# Generated by Django 5.2.4 on 2025-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_specialist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='num_cabinet',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
